export interface Team {
  team_key: string;
  game_code: string;
  start_date: number;
  end_date: number;
  num_teams: number;
  weekly_deadline: string | number;
  faab_balance: number;
  waiver_rule: string;
  current_weekly_adds: number;
  current_season_adds: number;
  scoring_type: string;
  edit_key: string;
  max_weekly_adds: number;
  max_season_adds: number;
  max_games_played: number;
  max_innings_pitched: number;
  game_name: string;
  game_season: string;
  game_is_over: boolean;
  team_name: string;
  team_url: string;
  team_logo: string;
  league_name: string;
  rank: string | number;
  points_for: string | number;
  points_against: string | number;
  points_back: string | number;
  outcome_totals: {
    wins: string | number;
    losses: string | number;
    ties: string | number;
    percentage: string | number;
  };
  is_subscribed: boolean;
  is_setting_lineups: boolean;
  last_updated: number;
  allow_transactions: boolean;
  allow_dropping: boolean;
  allow_adding: boolean;
  allow_add_drops: boolean;
  allow_waiver_adds: boolean;
}
